### ISSUE TITLE
std::unordered_map failure to compile under g++

### ISSUE THREAD

**Issue by jcsweitzer** [jmikeowen/spheral#8]
I will try to submit a pull request and fix this myself once I learn how to operate git, but I am running up against a wall trying to compile under Ubuntu with GCC 5.4.0 due to use of std::unordered_map being unhashed.  It appears that direct swapping for boost::unordered_map resolves the issue.

**Comment by mdavis36** [comment]
I've run into this issue before. Have you tried gcc8 (that's what I typically use now), or do you need to use 5.4.0 for a specific reason? I noticed we are using boost::unordered_map in TreeGravity and Mesh already so perhaps switching to a uniform implementation across the code wouldn't be the worst idea. However I would like to find out if there are any major performance differences between the std and boost implementations.

**Comment by jcsweitzer** [comment]
No good reason, other than that's what comes out of the repos.  I will give it a shot, thanks.

**Comment by jcsweitzer** [comment]
Compiles under gcc 7.4.0

**Comment by jmikeowen** [comment]
Well gee, I need to keep up on these issues better.  mdavis is correct -- we've been trying to switch from the boost:: versions of these data types to the std:: versions across the code, since modern C++ compilers have these data types built into the standard now.   I can see I need to go root these out from more places, but it does mean you need to use an up to date C++ compiler these days.
