### ISSUE TITLE
Boundary compilation

### ISSUE THREAD

**Issue by jcsweitzer** [jmikeowen/spheral#9]
Looks like there's a combination of a typo and a namespace error under Boundary.  The makefile adds
$(srcdir)/ConstantZVelocityBoundaryInst.cc to INSTSRCTARGETS, but I think it should be  $(srcdir)/ConstantZVelocityBoundaryInst.cc.py 

Also, in  ConstanZVelocityBoundaryInst.cc.py it looks like the instantiation should be done directly under the Spheral namespace, instead of under the BoundarySpace namespace.

This could just be my own ignorance.

**Comment by mdavis36** [comment]
The `INSTSRCTARGETS` list is used to run a python script to generate .cc files based on the configured number of dimensions. For each dimension it creates a separate <myFileNameHere>InstNd.cc where N is the given dimension passed into the template class argument.

In this case `ConstantZVelocityBoundaryInst.cc` is added to `INSTSRCTARGETS` because `ConstantZVelocityBoundary` is only used when building 3D spheral. Since it does not need to be instantiated for the 1D or 2D build the instantiation script is skipped so no `.py` file is technically needed or used during the build. You'll notice in `ConstantZVelocityBoundaryInst.cc` that `3` has already been passed to the template class definition.

**Comment by jcsweitzer** [comment]
Gotcha... I figured it was my ignorance somehow.  I was building in the src directory, which screws up the build system.
